language: rust
rust:
  - stable

cache: cargo

os:
  - linux
  - osx
  - windows

branches:
  only:
    - master

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install gnupg-modern; fi

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then gpgconf --kill dirmngr; fi
